// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Package { name: string, description: string, template: string, version: string, authors: Array<string>, license: string | null, }