// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

export interface Permission { key: string, level: PermissionLevel, targets: Array<string>, }