// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Software { scope: string, upstream: string, category: string, arch: string | null, language: string, main_program: string | null, tags: Array<string> | null, }